/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContribuintesRouteImport } from './routes/contribuintes'
import { Route as DebitosRouteImport } from './routes/debitos'
import { Route as FiscalizacoesRouteImport } from './routes/fiscalizacoes'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SegundoCerebroRouteImport } from './routes/segundo-cerebro'
import { Route as ContribuintesTaxpayerIdRouteImport } from './routes/contribuintes_.$taxpayerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuintesRoute = ContribuintesRouteImport.update({
  id: '/contribuintes',
  path: '/contribuintes',
  getParentRoute: () => rootRouteImport,
} as any)
const DebitosRoute = DebitosRouteImport.update({
  id: '/debitos',
  path: '/debitos',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalizacoesRoute = FiscalizacoesRouteImport.update({
  id: '/fiscalizacoes',
  path: '/fiscalizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SegundoCerebroRoute = SegundoCerebroRouteImport.update({
  id: '/segundo-cerebro',
  path: '/segundo-cerebro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuintesTaxpayerIdRoute = ContribuintesTaxpayerIdRouteImport.update({
  id: '/contribuintes_/$taxpayerId',
  path: '/contribuintes/$taxpayerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contribuintes': typeof ContribuintesRoute
  '/debitos': typeof DebitosRoute
  '/fiscalizacoes': typeof FiscalizacoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/portal': typeof PortalRoute
  '/relatorios': typeof RelatoriosRoute
  '/segundo-cerebro': typeof SegundoCerebroRoute
  '/contribuintes/$taxpayerId': typeof ContribuintesTaxpayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contribuintes': typeof ContribuintesRoute
  '/debitos': typeof DebitosRoute
  '/fiscalizacoes': typeof FiscalizacoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/portal': typeof PortalRoute
  '/relatorios': typeof RelatoriosRoute
  '/segundo-cerebro': typeof SegundoCerebroRoute
  '/contribuintes/$taxpayerId': typeof ContribuintesTaxpayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contribuintes': typeof ContribuintesRoute
  '/debitos': typeof DebitosRoute
  '/fiscalizacoes': typeof FiscalizacoesRoute
  '/notificacoes': typeof NotificacoesRoute
  '/portal': typeof PortalRoute
  '/relatorios': typeof RelatoriosRoute
  '/segundo-cerebro': typeof SegundoCerebroRoute
  '/contribuintes_/$taxpayerId': typeof ContribuintesTaxpayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/contribuintes'
    | '/debitos'
    | '/fiscalizacoes'
    | '/notificacoes'
    | '/portal'
    | '/relatorios'
    | '/segundo-cerebro'
    | '/contribuintes/$taxpayerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/contribuintes'
    | '/debitos'
    | '/fiscalizacoes'
    | '/notificacoes'
    | '/portal'
    | '/relatorios'
    | '/segundo-cerebro'
    | '/contribuintes/$taxpayerId'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/configuracoes'
    | '/contribuintes'
    | '/debitos'
    | '/fiscalizacoes'
    | '/notificacoes'
    | '/portal'
    | '/relatorios'
    | '/segundo-cerebro'
    | '/contribuintes_/$taxpayerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContribuintesRoute: typeof ContribuintesRoute
  DebitosRoute: typeof DebitosRoute
  FiscalizacoesRoute: typeof FiscalizacoesRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PortalRoute: typeof PortalRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SegundoCerebroRoute: typeof SegundoCerebroRoute
  ContribuintesTaxpayerIdRoute: typeof ContribuintesTaxpayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuintes': {
      id: '/contribuintes'
      path: '/contribuintes'
      fullPath: '/contribuintes'
      preLoaderRoute: typeof ContribuintesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debitos': {
      id: '/debitos'
      path: '/debitos'
      fullPath: '/debitos'
      preLoaderRoute: typeof DebitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscalizacoes': {
      id: '/fiscalizacoes'
      path: '/fiscalizacoes'
      fullPath: '/fiscalizacoes'
      preLoaderRoute: typeof FiscalizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segundo-cerebro': {
      id: '/segundo-cerebro'
      path: '/segundo-cerebro'
      fullPath: '/segundo-cerebro'
      preLoaderRoute: typeof SegundoCerebroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuintes_/$taxpayerId': {
      id: '/contribuintes_/$taxpayerId'
      path: '/contribuintes/$taxpayerId'
      fullPath: '/contribuintes/$taxpayerId'
      preLoaderRoute: typeof ContribuintesTaxpayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContribuintesRoute: ContribuintesRoute,
  DebitosRoute: DebitosRoute,
  FiscalizacoesRoute: FiscalizacoesRoute,
  NotificacoesRoute: NotificacoesRoute,
  PortalRoute: PortalRoute,
  RelatoriosRoute: RelatoriosRoute,
  SegundoCerebroRoute: SegundoCerebroRoute,
  ContribuintesTaxpayerIdRoute: ContribuintesTaxpayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
